apiVersion: skaffold/v1beta1
kind: Config
build:
  artifacts:
  - image: registry.k8.wildwidewest.xyz/repository/docker-repository/opus/books-gui
deploy:
  helm:
    releases:
    - name: books-gui-int
      chartPath: ../charts/books-gui
      setValues:
        h2.enabled: false
      setValueTemplates:
        image.tag: "{{.DIGEST}}"
      overrides:
        books-api:
          image:
            repository: registry.k8.wildwidewest.xyz/repository/docker-repository/opus/books-gui
        ingress:
          secretName: books-gui-int-secret
          hosts:
          - books-gui-int.k8.wildwidewest.xyz
          tls:
          - hosts:
            - books-gui-int.k8.wildwidewest.xyz
            secretName: books-gui-int-secret
          annotations:
            nginx.ingress.kubernetes.io/auth-secret: books-gui-int-basicauthsecret