apiVersion: skaffold/v1beta1
kind: Config
build:
  artifacts:
  - image: localhost:5000/opus-books-gui
deploy:
  helm:
    releases:
    - name: books-gui
      chartPath: ../charts/books-gui
      setValues:
        ingress.enabled: false
        h2.enabled: false
        image.repository: kube-registry:5000/opus-books-gui
        service.type: NodePort
      setValueTemplates:
        image.tag: "{{.DIGEST}}"
